#!/bin/bash -ex
function run_silently() {
    set +ex
    $@ >output.txt 2>&1
    EXIT_CODE=$?
    set -e

    if [ $EXIT_CODE != 0 ]; then
        echo "Non-zero exit code: $EXIT_CODE"
        cat output.txt
        exit $EXIT_CODE
    fi
    set -x
}

run_silently apt update
run_silently apt install -y libpq-dev tree

run_silently pip install -r /app/requirements.txt django ${ADDITIONAL_REQUIREMENTS}
run_silently pip install -e . 'importlib-metadata<5'
pip freeze

cd test_app
export DJANGO_SETTINGS_MODULE=test_app.settings

rm -rf ./test_app/shared/migrations
run_silently ./manage.py makemigrations
celery -A tenant_schemas_celery.test_app:app worker -l INFO &
pytest ../tenant_schemas_celery
