#!/bin/bash
pyenv activate tenant-schemas-celery
cd test_app
export DJANGO_SETTINGS_MODULE=test_app.settings

celery -A test_app.celery_app:app worker -l INFO -B --scheduler=tenant_schemas_celery.db_scheduler.TenantAwareDatabaseScheduler
