version: "3.6"
services:
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=qwe123
      - POSTGRES_USER=tenant_celery
      - POSTGRES_DB=tenant_celery
    logging:
      driver: "none"

  rabbitmq:
    image: rabbitmq
    logging:
      driver: "none"

  app:
    image: "python:${PYTHON_VERSION:-3.6}-slim"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - DATABASE_HOST=postgres
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - TENANT_SCHEMAS=${TENANT_SCHEMAS:-django-tenants}

    volumes:
      - ./tenant_schemas_celery:/app/tenant_schemas_celery
      - ./test_app:/app/test_app
      - ./requirements.txt:/app/requirements.txt
      - ./__app_run_tests:/app/__app_run_tests
      - ./setup.py:/app/setup.py
      - ./VERSION:/app/VERSION
      - ./README.md:/app/README.md

    command: ["bash", "-c", "cd /app && ./__app_run_tests"]
