# Generated by Django 3.0.2 on 2020-01-18 15:16

from django.db import migrations, models
try:
    import tenant_schemas.postgresql_backend.base as base
except ImportError:
    import django_tenants.postgresql_backend.base as base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[base._check_schema_name])),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
